export const dummyData = {
  avatar_url: "https://avatars.githubusercontent.com/u/65550334?v=4",
  bio: null,
  blog: "",
  company: null,
  created_at: "2020-05-18T14:02:13Z",
  email: null,
  events_url: "https://api.github.com/users/dasanchez11/events{/privacy}",
  followers: 0,
  followers_url: "https://api.github.com/users/dasanchez11/followers",
  following: 0,
  following_url:
    "https://api.github.com/users/dasanchez11/following{/other_user}",
  gists_url: "https://api.github.com/users/dasanchez11/gists{/gist_id}",
  gravatar_id: "",
  hireable: null,
  html_url: "https://github.com/dasanchez11",
  id: 65550334,
  location: null,
  login: "dasanchez11",
  name: null,
  node_id: "MDQ6VXNlcjY1NTUwMzM0",
  organizations_url: "https://api.github.com/users/dasanchez11/orgs",
  public_gists: 0,
  public_repos: 38,
  received_events_url:
    "https://api.github.com/users/dasanchez11/received_events",
  repos_url: "https://api.github.com/users/dasanchez11/repos",
  site_admin: false,
  starred_url:
    "https://api.github.com/users/dasanchez11/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dasanchez11/subscriptions",
  twitter_username: null,
  type: "User",
  updated_at: "2022-07-24T07:05:54Z",
  url: "https://api.github.com/users/dasanchez11",
};
